server:
  port: ${PORT:5001}

logging:
  level:
    root: INFO

spring:
  # Настраиваем подключение к базе данных
  datasource:
    url: jdbc:h2:./hexlet
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  # Настраиваем инструмент Liquibase
  # Указываем путь к основному файлу миграции
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

  # Настраиваем консоль Н2
  # Это позволит нам открыть её в браузере по указанному пути
  h2:
    console:
      enabled: true
      # Указываем путь, по которому будет открываться консоль
      path: /h2console/
      settings:
        web-allow-others: true